""" if there are two elements with the same type like attack and use item, then use xpath.
if there is only one submit type, then use 'input[type='submit'] in css selector
If you're here from reddit. Please note that I added all these explicityl_wait functions after trying a lot of things.
I want the function to keep battling rebattling the opponenet until I manually stop the script from running.
Also, this is an example account for the website."""
def exphoarder():
    from selenium import webdriver
    browser = webdriver.Chrome(r'C:\Users\Blacktooth\Downloads\chromedriver_win32\chromedriver.exe')
    browser.get("https://www.pokemon-vortex.com")
    login = browser.find_element_by_class_name("login-header")
    login.click()
    username = browser.find_element_by_id("myusername")
    username.send_keys("trflying")
    password = browser.find_element_by_id("mypassword")
    password.send_keys("trflying")
    submit = browser.find_element_by_id("submit")
    submit.click()
    browser.get("https://www.pokemon-vortex.com/battle-search/")
    training_account = browser.find_element_by_name("buser")
    training_account.send_keys("AvSteel")
    battle = browser.find_element_by_name("submitb")
    battle.click()
    browser.maximize_window()
    while 0 != 1:
        browser.implicitly_wait(8)
        browser.execute_script("window.scrollBy(0,720);")
        browser.implicitly_wait(8)
        cont1 = browser.find_element_by_css_selector('input[type="submit"]')
        cont1.click()
        browser.implicitly_wait(8)
        browser.execute_script("window.scrollBy(0,300);")
        browser.implicitly_wait(8)
        atck1 = browser.find_element_by_xpath('/html/body/div[5]/div/div[2]/form[2]/div/input')
        atck1.click()
        browser.implicitly_wait(8)
        browser.execute_script("window.scrollBy(0,300);")
        browser.implicitly_wait(8)
        cont2 = browser.find_element_by_css_selector('input[type="submit"]')
        cont2.click()
        browser.implicitly_wait(8)
        browser.execute_script("window.scrollBy(0,720);")
        browser.implicitly_wait(8)
        cont3 = browser.find_element_by_css_selector('input[type="submit"]')
        cont3.click()
        browser.implicitly_wait(8)
        browser.execute_script("window.scrollBy(0,300);")
        browser.implicitly_wait(8)
        atck2 = browser.find_element_by_xpath('/html/body/div[5]/div/div[2]/form[2]/div/input')
        atck2.click()
        browser.implicitly_wait(8)
        browser.execute_script("window.scrollBy(0,300);")
        browser.implicitly_wait(8)
        cont4 = browser.find_element_by_css_selector('input[type="submit"]')
        cont4.click()
        browser.implicitly_wait(8)
        browser.execute_script("window.scrollBy(0,720);")
        browser.implicitly_wait(8)
        cont5 = browser.find_element_by_css_selector('input[type="submit"]')
        cont5.click()
        browser.implicitly_wait(8)
        browser.execute_script("window.scrollBy(0,300);")
        browser.implicitly_wait(8)
        atck3 = browser.find_element_by_xpath('/html/body/div[5]/div/div[2]/form[2]/div/input')
        atck3.click()
        browser.implicitly_wait(8)
        browser.execute_script("window.scrollBy(0,300);")
        browser.implicitly_wait(8)
        cont6 = browser.find_element_by_css_selector('input[type="submit"]')
        cont6.click()
        browser.implicitly_wait(8)
        browser.execute_script("window.scrollBy(0,720);")
        browser.implicitly_wait(8)
        cont7 = browser.find_element_by_css_selector('input[type="submit"]')
        cont7.click()
        browser.implicitly_wait(8)
        browser.execute_script("window.scrollBy(0,300);")
        browser.implicitly_wait(8)
        atck4 = browser.find_element_by_xpath('/html/body/div[5]/div/div[2]/form[2]/div/input')
        atck4.click()
        browser.implicitly_wait(8)
        browser.execute_script("window.scrollBy(0,300);")
        browser.implicitly_wait(8)
        cont8 = browser.find_element_by_css_selector('input[type="submit"]')
        cont8.click()
        browser.implicitly_wait(8)
        browser.execute_script("window.scrollBy(0,720);")
        browser.implicitly_wait(8)
        cont9 = browser.find_element_by_css_selector('input[type="submit"]')
        cont9.click()
        browser.implicitly_wait(8)
        browser.execute_script("window.scrollBy(0,300);")
        browser.implicitly_wait(8)
        atck5 = browser.find_element_by_xpath('/html/body/div[5]/div/div[2]/form[2]/div/input')
        atck5.click()
        browser.implicitly_wait(8)
        browser.execute_script("window.scrollBy(0,300);")
        browser.implicitly_wait(8)
        cont10 = browser.find_element_by_css_selector('input[type="submit"]')
        cont10.click()
        browser.implicitly_wait(8)
        browser.execute_script("window.scrollBy(0,720);")
        browser.implicitly_wait(8)
        cont11 = browser.find_element_by_css_selector('input[type="submit"]')
        cont11.click()
        browser.implicitly_wait(8)
        browser.execute_script("window.scrollBy(0,300);")
        browser.implicitly_wait(8)
        atck6 = browser.find_element_by_xpath('/html/body/div[5]/div/div[2]/form[2]/div/input')
        atck6.click()
        browser.implicitly_wait(8)
        browser.execute_script("window.scrollBy(0,300);")
        browser.implicitly_wait(8)
    
        cont12 = browser.find_element_by_css_selector('input[type="submit"]')
        cont12.click()
        rebattle = browser.find_element_by_link_text("Rebattle Opponent")
    
    
    
    
exphoarder()
    
        
